name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: trunk-action
      uses: jetli/trunk-action@v0.4.0
      with:
        version: latest
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        # Rust toolchain name.
        target: wasm32-unknown-unknown
    - name: Build
      run: cd view && trunk build --release
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        target_branch: gh-pages
        build_dir: view/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}